live_config_reload = true
working_directory = "None"

# Themes --
import = ["/home/jlekhram/.config/alacritty/alacritty-themes/gruvbox_dark.toml"]

[window]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 0.9
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape = "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "IBM Plex Mono Medm"
normal.style = "Regular"
size = 12.0

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"
