# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

alias ff=fastfetch
alias gl='ssh gl.umbc.edu -l jlekhra1'
alias l=ll


eval "$(starship init bash)"

export PATH=$PATH:~/.cargo/bin/

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/jlekhram/.lmstudio/bin"
# End of LM Studio CLI section

